---
deployment:
  tasks:
    - cd /home/kaizpwij/nyakaju-repo && PATH=/opt/alt/alt-nodejs22/root/usr/bin:$PATH /opt/alt/alt-nodejs22/root/usr/bin/npm install
    - cd /home/kaizpwij/nyakaju-repo && PATH=/opt/alt/alt-nodejs22/root/usr/bin:$PATH /opt/alt/alt-nodejs22/root/usr/bin/npm run build
    - /usr/bin/touch /home/kaizpwij/nyakaju-repo/tmp/restart.txt